server:
  port: 9898
spring:
  servlet:
    multipart:
      max-request-size: 10MB #上传文件总的最大值
      max-file-size: 1MB #单个文件的最大值
  thymeleaf:
    cache: false #不开启缓存
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sponge?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      # 连接池配置 初始化池大小，最小，最大数
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 6000
      pool-prepared-statements: true
      #
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在连接池中最小的生存时间
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      filters: stat
      filter:
        # 慢SQL记录(sql语句执行时间超过某个界限就记录下来)
        stat:
          slow-sql-millis: 200
          log-slow-sql: true
      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
        login-username: admin
        login-password: admin
        allow:
        deny:

mybatis:
  mapper-locations: classpath:mybatis/*.xml #指明mapper配置文件路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名

blog:
  limit:
    page-size: 10 #自定义属性，用于规定分页查询每页显示的条数
